import type { DesignPreset, DesignPresetId } from "./types";

export const DESIGN_PRESETS: Record<DesignPresetId, DesignPreset> = {
  elegant: {
    id: "elegant",
    name: "Elegant",
    description: "Serif + Orchid + Soft — look sofisticato e raffinato per studi di alta gamma",
    palette: {
      primary: "#7C3AED",
      primaryForeground: "#FAF5FF",
      secondary: "#F3E8FF",
      secondaryForeground: "#581C87",
      background: "#FDFCFB",
      foreground: "#1F2937",
      muted: "#F5F3FF",
      mutedForeground: "#6B7280",
      border: "#E5E7EB",
      accent: "#C084FC",
      accentForeground: "#FFFFFF",
      card: "#FFFFFF",
      cardForeground: "#111827",
    },
    typography: {
      headingFont: "serif",
      bodyFont: "sans",
      headingScale: 1.3,
      bodyLineHeight: 1.7,
      fontWeightHeading: 600,
      fontWeightBody: 400,
    },
    layout: {
      radius: "lg",
      shadow: "soft",
      spacing: "comfortable",
      containerMaxWidth: "max-w-5xl",
      density: "comfortable",
      motion: "subtle",
      sectionStyle: "card",
      buttonStyle: "shadow",
      photographyStyle: "warm",
      bodyMaxWidth: 1140,
    },
  },
  soft_beauty: {
    id: "soft_beauty",
    name: "Soft Beauty",
    description: "Sans + Rose + Rounded — look delicato e femminile per centri estetici",
    palette: {
      primary: "#EC4899",
      primaryForeground: "#FFF1F2",
      secondary: "#FCE7F3",
      secondaryForeground: "#9D174D",
      background: "#FFFAFA",
      foreground: "#1F2937",
      muted: "#FFF1F2",
      mutedForeground: "#6B7280",
      border: "#FBCFE8",
      accent: "#F472B6",
      accentForeground: "#FFFFFF",
      card: "#FFFFFF",
      cardForeground: "#111827",
    },
    typography: {
      headingFont: "sans",
      bodyFont: "sans",
      headingScale: 1.2,
      bodyLineHeight: 1.6,
      fontWeightHeading: 700,
      fontWeightBody: 400,
    },
    layout: {
      radius: "xl",
      shadow: "soft",
      spacing: "comfortable",
      containerMaxWidth: "max-w-4xl",
      density: "comfortable",
      motion: "default",
      sectionStyle: "card",
      buttonStyle: "solid",
      photographyStyle: "vivid",
      bodyMaxWidth: 1024,
    },
  },
  barber_strong: {
    id: "barber_strong",
    name: "Barber Strong",
    description: "Display + Black + Gold + Sharp — look deciso e maschile per barbieri",
    palette: {
      primary: "#D4AF37",
      primaryForeground: "#0A0A0A",
      secondary: "#1F1F1F",
      secondaryForeground: "#F5F5DC",
      background: "#0A0A0A",
      foreground: "#F5F5F5",
      muted: "#1A1A1A",
      mutedForeground: "#9CA3AF",
      border: "#2D2D2D",
      accent: "#8B7355",
      accentForeground: "#FFFFFF",
      card: "#121212",
      cardForeground: "#F5F5F5",
    },
    typography: {
      headingFont: "display",
      bodyFont: "sans",
      headingScale: 1.4,
      bodyLineHeight: 1.6,
      fontWeightHeading: 800,
      fontWeightBody: 500,
    },
    layout: {
      radius: "none",
      shadow: "sharp",
      spacing: "compact",
      containerMaxWidth: "max-w-6xl",
      density: "compact",
      motion: "subtle",
      sectionStyle: "raised",
      buttonStyle: "solid",
      photographyStyle: "mono",
      bodyMaxWidth: 1200,
    },
  },
  minimal: {
    id: "minimal",
    name: "Minimal",
    description: "Sans + Neutral + Flat — pulito, essenziale, contenuto al primo posto",
    palette: {
      primary: "#111827",
      primaryForeground: "#FFFFFF",
      secondary: "#F3F4F6",
      secondaryForeground: "#111827",
      background: "#FFFFFF",
      foreground: "#111827",
      muted: "#F9FAFB",
      mutedForeground: "#6B7280",
      border: "#E5E7EB",
      accent: "#374151",
      accentForeground: "#FFFFFF",
      card: "#FFFFFF",
      cardForeground: "#111827",
    },
    typography: {
      headingFont: "sans",
      bodyFont: "sans",
      headingScale: 1.1,
      bodyLineHeight: 1.6,
      fontWeightHeading: 600,
      fontWeightBody: 400,
    },
    layout: {
      radius: "md",
      shadow: "flat",
      spacing: "default",
      containerMaxWidth: "max-w-5xl",
      density: "default",
      motion: "none",
      sectionStyle: "minimal",
      buttonStyle: "outline",
      photographyStyle: "natural",
      bodyMaxWidth: 1140,
    },
  },
  editorial: {
    id: "editorial",
    name: "Editorial",
    description:
      "Serif Heading + Sans Body, Contrasto Alto, Grandi Immagini — look magazine per parrucchieri high-end",
    palette: {
      primary: "#B91C1C",
      primaryForeground: "#FAFAF9",
      secondary: "#FEF2F2",
      secondaryForeground: "#7F1D1D",
      background: "#FAFAF9",
      foreground: "#0C0A09",
      muted: "#F5F5F4",
      mutedForeground: "#57534E",
      border: "#E7E5E4",
      accent: "#78350F",
      accentForeground: "#FFFFFF",
      card: "#FFFFFF",
      cardForeground: "#1C1917",
    },
    typography: {
      headingFont: "serif",
      bodyFont: "sans",
      headingScale: 1.4,
      bodyLineHeight: 1.7,
      fontWeightHeading: 500,
      fontWeightBody: 400,
    },
    layout: {
      radius: "md",
      shadow: "soft",
      spacing: "comfortable",
      containerMaxWidth: "max-w-6xl",
      density: "comfortable",
      motion: "subtle",
      sectionStyle: "card",
      buttonStyle: "outline",
      photographyStyle: "warm",
      bodyMaxWidth: 1280,
    },
  },
  warm_natural: {
    id: "warm_natural",
    name: "Warm & Natural",
    description: "Colori Terra, Rounded, Sans Rounded — atmosfera accogliente per benessere e SPA",
    palette: {
      primary: "#A16207",
      primaryForeground: "#FEFCE8",
      secondary: "#FEF3C7",
      secondaryForeground: "#713F12",
      background: "#FFFBF5",
      foreground: "#292524",
      muted: "#FAF5EC",
      mutedForeground: "#78716C",
      border: "#EFE4D4",
      accent: "#C2410C",
      accentForeground: "#FFFFFF",
      card: "#FFFFFF",
      cardForeground: "#1C1917",
    },
    typography: {
      headingFont: "sans",
      bodyFont: "sans",
      headingScale: 1.2,
      bodyLineHeight: 1.7,
      fontWeightHeading: 600,
      fontWeightBody: 400,
    },
    layout: {
      radius: "xl",
      shadow: "soft",
      spacing: "comfortable",
      containerMaxWidth: "max-w-5xl",
      density: "comfortable",
      motion: "default",
      sectionStyle: "card",
      buttonStyle: "solid",
      photographyStyle: "warm",
      bodyMaxWidth: 1140,
    },
  },
  luxury: {
    id: "luxury",
    name: "Luxury",
    description:
      "Contrasto Elevato, Bianco/Nero, Accento Prezioso, Serif — stampa high-end, lusso, brand esclusivi",
    palette: {
      primary: "#0A0A0A",
      primaryForeground: "#FFFFFF",
      secondary: "#18181B",
      secondaryForeground: "#FAFAFA",
      background: "#FFFFFF",
      foreground: "#09090B",
      muted: "#FAFAFA",
      mutedForeground: "#52525B",
      border: "#D4D4D8",
      accent: "#B8860B",
      accentForeground: "#FFFFFF",
      card: "#FFFFFF",
      cardForeground: "#18181B",
    },
    typography: {
      headingFont: "serif",
      bodyFont: "sans",
      headingScale: 1.3,
      bodyLineHeight: 1.6,
      fontWeightHeading: 400,
      fontWeightBody: 300,
    },
    layout: {
      radius: "sm",
      shadow: "flat",
      spacing: "comfortable",
      containerMaxWidth: "max-w-6xl",
      density: "default",
      motion: "subtle",
      sectionStyle: "minimal",
      buttonStyle: "outline",
      photographyStyle: "natural",
      bodyMaxWidth: 1280,
    },
  },
};

export const DESIGN_PRESET_LIST: DesignPreset[] = [
  DESIGN_PRESETS.elegant,
  DESIGN_PRESETS.soft_beauty,
  DESIGN_PRESETS.barber_strong,
  DESIGN_PRESETS.minimal,
  DESIGN_PRESETS.editorial,
  DESIGN_PRESETS.warm_natural,
  DESIGN_PRESETS.luxury,
];

export function getDesignPreset(id: string | null | undefined): DesignPreset {
  if (id && id in DESIGN_PRESETS) {
    return DESIGN_PRESETS[id as DesignPresetId];
  }
  return DESIGN_PRESETS.minimal;
}
